<a href="https://colab.research.google.com/github/Metodoscomputacionales1/Metodos1_PedroAngarita_SimonUribe/blob/main/Tarea4%20/Factorizacion_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

In [25]:
A = np.array([[4.,-2.,1.],[20.,-7.,12.],[-8.,13.,17.]])
A

array([[ 4., -2.,  1.],
       [20., -7., 12.],
       [-8., 13., 17.]])

In [28]:
def LU(A_, ones = False):

  A = A_.copy()
  n = A.shape[0]
  z=np.zeros([n,n])
  for i in range(n):
    z[i,i]=1

  for i in range(n+1):


    for j in range(i+1,n):
      a = A[j,i]/A[i,i]

      z[j, i] = a

      A[j,:] -= a*A[i,:]

  return z,A

In [29]:
LU(A)

(array([[ 1.,  0.,  0.],
        [ 5.,  1.,  0.],
        [-2.,  3.,  1.]]),
 array([[ 4., -2.,  1.],
        [ 0.,  3.,  7.],
        [ 0.,  0., -2.]]))

In [35]:
a,_=LU(A)
_,B=LU(A)



In [36]:
a@B

array([[ 4., -2.,  1.],
       [20., -7., 12.],
       [-8., 13., 17.]])