<a href="https://colab.research.google.com/github/Metodoscomputacionales1/Metodos1_PedroAngarita_SimonUribe/blob/main/Parcial2/Apuestas%20algoritmo%20genetico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time
import copy

In [ ]:
def Plotter(e):

  fig = plt.figure(figsize=(5,5))
  ax = fig.add_subplot(111)
  ax.set_title('Epoch: {:.0f}'.format(e),fontsize=10)

  return fig,ax

In [ ]:
cuotas=np.array([8.51, 10.68, 12.24, 13.66, 15.37, 17.15, 19.66, 24.69])

w = np.array([0.185, 0.152, 0.137, 0.125, 0.116, 0.107, 0.096, 0.082])


In [ ]:
def retorn(w,c,ca=1000000):
  z=np.zeros(np.shape(w)[0])
  for i in  range(np.shape(w)[0]):
    z[i]=(w[i]*c[i]-1) *ca

  return  np.min(z)



In [ ]:
retorn(w,cuotas)

574349.9999999999

In [ ]:
class Robot:


  def __init__(self, f, Id=0):

    self.Id = Id
    self.f = retorn
    self.cuotas = cuotas


    self.r = np.random.uniform(0.,1., size=self.cuotas.shape[0])
    self.r = self.r / np.sum(self.r)


  def GetR(self):
    return self.r



  def Mutate(self):

    self.r += np.random.normal(loc=0., scale=0.01, size=self.cuotas.shape[0])
    self.r = np.abs(self.r) # Asegura que no haya valores negativos
    self.r = self.r / np.sum(self.r) # Normaliza para que la suma sea 1

  def SetFitness(self):
    self.fitness = self.f(self.r,self.cuotas)
  @property
  def Fitness(self):
    return self.fitness

  def __repr__(self):
    return f"Robot {self.Id}"

In [ ]:
r=Robot(retorn)
r.GetR()

array([0.19373912, 0.1070981 , 0.20922158, 0.17343014, 0.01427574,
       0.19974458, 0.05278999, 0.04970076])

In [ ]:
def GetRobots(N):

  Robots = []

  for i in range(N):
    r = Robot(retorn,i)
    Robots.append(r)

  return Robots

In [ ]:
a=[1,2,3,4,5,6]
a[:2]

[1, 2]

In [ ]:
robots=GetRobots(5)
for i, p in enumerate(robots):
        p.Mutate()
        p.SetFitness()

score = [ (p.Fitness, p) for p in robots ]
score = sorted(score, key=lambda x: x[0], reverse=True)
score


[(-220699.38256570988, Robot 3),
 (-615979.5737439155, Robot 0),
 (-719500.7280314609, Robot 4),
 (-805009.9047892118, Robot 1),
 (-865861.4246477318, Robot 2)]

In [298]:
def apuestass2(Robots, epochs=500):

  N = int(0.8*len(Robots))

  for e in range(epochs):



    # Mutamoss
    for i, p in enumerate(Robots):
      p.Mutate()
      p.SetFitness()

    # lista por tupla, valor en funcion y robot
    score = [ (p.Fitness, p) for p in Robots ]
    #ordenamos las tuplas por mayo valor en la funcion
    score = sorted(score, key=lambda x: x[0], reverse=True) # De menor a mayor

    #listamos los 80% mejores
    Temp = [r[1] for i, r in enumerate(score) if i < N]

     # Reintroducción aleatoria 20% de algunos individuos
    for i in range(int(0.2 * len(Robots))):
        Robots[i] = Robot(retorn, i)
    # se ingresan los mejores de la iteracion
    for i,r in enumerate(Robots):
      j = i%N
      Robots[i] = copy.deepcopy(Temp[j])


    return Robots

In [299]:
robots=GetRobots(500
                 )

In [387]:
b=apuestass2(robots)
a=[]
for i in b:
  a.append((i.Fitness,i.GetR()))

d=a[0][1]
a[0]

(612239.0039529495,
 array([0.189809  , 0.1514037 , 0.13814342, 0.12518536, 0.10489519,
        0.1202977 , 0.09493271, 0.07533293]))

In [309]:
d

array([0.16353696, 0.13713821, 0.11601271, 0.14510014, 0.13547047,
       0.16576523, 0.07431336, 0.06266292])

In [389]:

retorn(d,cuotas)

612239.0039529495

In [391]:
# "d" representa el vector de poorcenrtajes en el cual se debe apostar en cada cota para maximizar su ganancia
#retornando una ganacia de 612 239.0039529495
#la cantidad de dinero en cada cota
d*1000000

array([189808.99817403, 151403.70119596, 138143.42370231, 125185.35938395,
       104895.18568334, 120297.69566926,  94932.71063215,  75332.925559  ])

In [399]:
d2=d*1000000


In [400]:
#tomemos cada caso y veamos que sucede si cae en cada una de las cotas
z=np.zeros(np.shape(w)[0])
for i in  range(np.shape(w)[0]):

  z[i]=(d2[i]*cuotas[i])
z

array([1615274.57446096, 1616991.52877282, 1690875.5061163 ,
       1710032.00918482, 1612239.00395295, 2063105.48072772,
       1866377.09102813, 1859969.93205174])

In [ ]:
#como vemos si distribuimos el millon de pesos en porcentajes que describe d
# sin importar donde caiga el caso, el pago de la inversion sera mayor que la inverion inicial de un millon
#e incluso se ganara dinero por la inversion