<a href="https://colab.research.google.com/github/Metodoscomputacionales1/Metodos1_PedroAngarita_SimonUribe/blob/main/Tarea3/Ejercicio15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym


In [39]:
def GetNewtonMethod(f,df,xn,itmax = 10000, precision=1e-14):

    error = 1.
    it = 0

    while error >= precision and it < itmax:

        try:

            xn1 = xn - f(xn)/df(xn)

            error = np.abs( (xn1-xn)/xn )
           # error = np.abs(f(xn)/df(xn))

        except ZeroDivisionError:
            print("zero division")

        xn  = xn1
        it += 1

    #print('Raiz:',xn,it)

    if it == itmax:
        return False
    else:
        return xn



In [40]:
def GetAllRoots(f,df,x, tolerancia=13):

    Roots = np.array([])

    for i in x:

        root = GetNewtonMethod(f,df,i)

        if root != False:

            croot = np.round( root, tolerancia )

            if croot not in Roots:
                Roots = np.append( Roots, croot )

    # Ordenamos las raices
    Roots.sort()

    return Roots

In [41]:
def GetLegendre(n):

  x = sym.Symbol('x',Real=True)
  y = sym.Symbol('y',Real=True)

  y = (x**2 - 1)**n

  p = sym.diff(y,x,n)/(2**n * np.math.factorial(n))

  return p

In [42]:
def GetRootsPolynomial(n,xi,poly,dpoly):

    x = sym.Symbol('x',Real=True)
    pn = sym.lambdify([x],poly[n],'numpy')
    dpn = sym.lambdify([x],dpoly[n],'numpy')
    Roots = GetAllRoots(pn,dpn,xi)
    Weights = 2/((1-Roots**2)*(dpn(Roots)**2))

    return Roots, Weights

In [43]:
Legendre = []
DLegendre = []

x = sym.Symbol('x',Real=True)
n=20

for i in range(n+1):

    poly = GetLegendre(i)

    Legendre.append(poly)
    DLegendre.append(sym.diff(poly,x))


<ipython-input-41-adbe1921b909>:8: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  p = sym.diff(y,x,n)/(2**n * np.math.factorial(n))


In [44]:
xi = np.linspace(-1,1,100)
Roots=[]
Weights=[]
for i in range(1,n+1):
    raices, pesos = GetRootsPolynomial(i,xi,Legendre,DLegendre)
    Roots.append(raices)
    Weights.append(pesos)
#Ceros de los primeros 20 polinomios de legendre

Roots


<ipython-input-39-b7688e483714>:12: RuntimeWarning: invalid value encountered in scalar divide
  error = np.abs( (xn1-xn)/xn )


[array([], dtype=float64),
 array([-0.57735027,  0.57735027]),
 array([-0.77459667,  0.77459667]),
 array([-0.86113631, -0.33998104,  0.33998104,  0.86113631]),
 array([-0.90617985, -0.53846931,  0.53846931,  0.90617985]),
 array([-0.93246951, -0.66120939, -0.23861919,  0.23861919,  0.66120939,
         0.93246951]),
 array([-0.94910791, -0.74153119, -0.40584515,  0.40584515,  0.74153119,
         0.94910791]),
 array([-0.96028986, -0.79666648, -0.52553241, -0.18343464,  0.18343464,
         0.52553241,  0.79666648,  0.96028986]),
 array([-0.96816024, -0.83603111, -0.61337143, -0.32425342,  0.32425342,
         0.61337143,  0.83603111,  0.96816024]),
 array([-0.97390653, -0.86506337, -0.67940957, -0.43339539, -0.14887434,
         0.14887434,  0.43339539,  0.67940957,  0.86506337,  0.97390653]),
 array([-0.97822866, -0.8870626 , -0.73015201, -0.51909613, -0.26954316,
         0.26954316,  0.51909613,  0.73015201,  0.8870626 ,  0.97822866]),
 array([-0.98156063, -0.90411726, -0.76990267

In [45]:
#Pesos ponderados
Weights

[array([], dtype=float64),
 array([1., 1.]),
 array([0.55555556, 0.55555556]),
 array([0.34785485, 0.65214515, 0.65214515, 0.34785485]),
 array([0.23692689, 0.47862867, 0.47862867, 0.23692689]),
 array([0.17132449, 0.36076157, 0.46791393, 0.46791393, 0.36076157,
        0.17132449]),
 array([0.12948497, 0.27970539, 0.38183005, 0.38183005, 0.27970539,
        0.12948497]),
 array([0.10122854, 0.22238103, 0.31370665, 0.36268378, 0.36268378,
        0.31370665, 0.22238103, 0.10122854]),
 array([0.08127439, 0.18064816, 0.2606107 , 0.31234708, 0.31234708,
        0.2606107 , 0.18064816, 0.08127439]),
 array([0.06667134, 0.14945135, 0.21908636, 0.26926672, 0.29552422,
        0.29552422, 0.26926672, 0.21908636, 0.14945135, 0.06667134]),
 array([0.05566857, 0.12558037, 0.18629021, 0.23319376, 0.26280454,
        0.26280454, 0.23319376, 0.18629021, 0.12558037, 0.05566857]),
 array([0.04717534, 0.10693933, 0.16007833, 0.20316743, 0.23349254,
        0.24914705, 0.24914705, 0.23349254, 0.2031674