<a href="https://colab.research.google.com/github/Metodoscomputacionales1/Metodos1_PedroAngarita_SimonUribe/blob/main/Tarea4/Punto_12_taller4_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [130]:

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time
import sympy as sym
from scipy.optimize import fsolve

In [131]:
def Plotter(e):

  fig = plt.figure(figsize=(6,3))
  ax = fig.add_subplot(121)
  ax1 = fig.add_subplot(122)

  ax.set_title('Epoch: {:.0f}'.format(e),fontsize=10)

  return fig,ax,ax1

In [132]:
G1=(lambda x,y:np.log(x**2+y**2)-np.sin(y*x)-np.log(2)-np.log(np.pi) , \
    lambda x,y: np.exp(x-y) + np.cos(x*y), \
   )

In [133]:
def GetF(G,r):

  n = r.shape[0]
  v = np.zeros(n)

  for i in range(n):
    v[i] = G[i](r[0],r[1])

  return v

In [153]:
def GetF2(G,r):

  n = r.shape[0]
  v = np.zeros(n)

  for i in range(n):
    v[i] = G[i](r[0],r[1],r[2])

  return v

In [154]:
GetF(G1,np.array([0,1]))

array([-1.83787707,  1.36787944])

In [155]:
def Metric(G,r):


  return 0.5*np.linalg.norm(GetF(G,r))**2

In [163]:
def Metric2(G,r):


  return 0.5*np.linalg.norm(GetF2(G,r))**2

In [156]:
Metric(G1,np.array([1,1]))

3.158762546031256

In [157]:
def GetJacobian(f,r,h=1e-3):

  n = r.shape[0]

  J = np.zeros((n,n))

  for i in range(n):
    for j in range(n):

      rf = r.copy()
      rb = r.copy()

      rf[j] = rf[j] + h
      rb[j] = rb[j] - h

      J[i,j] = (f[i](rf[0],rf[1]) - f[i](rb[0],rb[1]))/(2*h)

  return J

In [158]:
def GetJacobian2(f,r,h=1e-3):

  n = r.shape[0]

  J = np.zeros((n,n))

  for i in range(n):
    for j in range(n):

      rf = r.copy()
      rb = r.copy()

      rf[j] = rf[j] + h
      rb[j] = rb[j] - h

      J[i,j] = (f[i](rf[0],rf[1],rf[2]) - f[i](rb[0],rb[1],rb[2]))/(2*h)

  return J

In [159]:
GetJacobian(G1,np.array([1.,3.]))

array([[ 3.16997302,  1.58999234],
       [-0.28802408, -0.27645529]])

In [160]:
def Minimizer(G,r,lr=1e-4,epochs=int(1.5e5),error=1e-22):

  metric = 1
  it = 0

  M = np.array([])
  R = np.array([r])

  while metric > error and it < epochs:

    M = np.append(M,Metric(G,r))

    J = GetJacobian(G,r).T
    Vector = GetF(G,r)

    r = r - lr*np.dot(J,Vector)

    R = np.vstack((R,r))

    metric = Metric(G,r)





    it += 1

  return r,it

In [164]:
def Minimizer2(G,r,lr=1e-4,epochs=int(1.5e5),error=1e-22):

  metric = 1
  it = 0

  M = np.array([])
  R = np.array([r])

  while metric > error and it < epochs:

    M = np.append(M,Metric2(G,r))

    J = GetJacobian2(G,r).T
    Vector = GetF2(G,r)

    r = r - lr*np.dot(J,Vector)

    R = np.vstack((R,r))

    metric = Metric2(G,r)





    it += 1

  return r,it

In [169]:
xsol, it = Minimizer(G1,np.array([2,2]))


In [143]:
xsol

array([1.77245385, 1.77245385])

In [144]:
GetF(G1,xsol)#practimante 0

array([-2.22044605e-16, -1.41413548e-11])

In [145]:
it

110717

In [147]:
G2=(lambda x,y,z:6*x-(2*np.cos(y*z))-1 , \
    lambda x,y,z: 9*y+np.sqrt(x**2+np.sin(z)+1.06)+0.9, \
    lambda x,y,z: 60*z+3*np.exp(-1*x*y)+10*np.pi-3,
   )

In [166]:
solucion,it=Minimizer2(G2,np.array([0,0,0]))

In [167]:
solucion

array([ 0.49814468, -0.1996059 , -0.52882598])

In [168]:
GetF2(G2,solucion)#practicamente 0 de nuevo

array([-1.40900625e-11,  7.12430115e-13,  7.10542736e-15])