<a href="https://colab.research.google.com/github/Metodoscomputacionales1/Metodos1_PedroAngarita_SimonUribe/blob/main/Tarea4/Vectores%20y%20valores%20propios%20Jacobi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
import sympy as sp
import numpy as np
from ast import Break

In [203]:
A=np.array([[4,1,1],[1,3,2],[1,2,5]])
np.shape(A)[0]

3

In [217]:
def Vectores_valores_propios(A,itmax=10,tolerancia=1e-10):

    n =np.shape(A)[0]


    V = np.eye(n)

    for it in range(itmax):

        mayor = 0
        MI = 0
        MJ= 0
        for i in range(n):
            for j in range(i+1, n):
                if abs(A[i,j]) > abs(mayor):
                    mayor = A[i,j]
                    MI, MJ = i, j


        if abs(mayor) < tolerancia:
            break

        if A[MI,MI] == A[MJ,MJ]:
            theta = np.pi / 4
        else:
            theta = 0.5 * np.arctan(2 * A[MI,MJ] / (A[MI,MI] - A[MJ,MJ]))


        R = np.eye(n)
        R[MI,MI] = np.cos(theta)
        R[MJ,MJ] = np.cos(theta)
        R[MI,MJ] = -np.sin(theta)
        R[MJ,MI] = np.sin(theta)

        A = R.T @ A @ R
        V = V @ R


    valores = np.diag(A)


    vectores =[V[0],V[1],V[2]]

    return valores, vectores,it



In [218]:
Vectores_valores_propios(A)

(array([3.39729507, 1.70759841, 6.89510652]),
 [array([ 0.88573564, -0.17059871,  0.43170413]),
  array([-0.07589338,  0.86427949,  0.49725362]),
  array([-0.45794385, -0.47319874,  0.75257583])],
 8)

In [212]:
np.linalg.eig(A)

EigResult(eigenvalues=array([6.89510652, 3.39729507, 1.70759841]), eigenvectors=array([[ 0.43170413,  0.88573564,  0.17059871],
       [ 0.49725362, -0.07589338, -0.86427949],
       [ 0.75257583, -0.45794385,  0.47319874]]))

In [219]:
# la diferencia entre los metodos se situa en el orden de las filas, de la matriz R que determina los vectores propios,