<a href="https://colab.research.google.com/github/Metodoscomputacionales1/Metodos1_PedroAngarita_SimonUribe/blob/main/Tarea5/Ejercicio4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [123]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [124]:
os.chdir("/content/drive/MyDrive/Colab Notebooks/Datos/")
!ls

Exponencial.dat  MediaMovilData.csv  MinimosCuadratico.txt  MinimosLineal.txt


In [125]:
file = '/content/drive/MyDrive/Colab Notebooks/Datos/MinimosCuadratico.txt'
file

'/content/drive/MyDrive/Colab Notebooks/Datos/MinimosCuadratico.txt'

In [126]:
data = pd.read_csv(file)

In [127]:
data = pd.read_csv(file,sep=' ')
data.columns = ['x','y']

In [128]:
x = np.array(data['x'])
y = np.array(data['y'])

In [129]:
def GetFit(x,y,n):
  l=x.shape[0]
  b=y
  A=np.ones((l,n+1))
  for i in range(1,n+1):
    A[:,i]=x**i
    #Esto hace que cada columan sea el grado de x
  AT=np.dot(A.T,A)
  bT=np.dot(A.T,b)
  xsol=np.linalg.solve(AT,bT)

  return xsol

#primera columna 1s, la segunda xs, la tercesa seria x**2 y asi sucesivamente
sol1=GetFit(x,y,2)
sol1=np.flip(sol1)
sol1

array([3.04171871, 5.04229284, 3.91439388])

In [130]:
import numpy as np
from scipy.optimize import curve_fit

def GetModel(x, *p):
  y = 0.
  for n in range(len(p)):
    y += p[n] * x**n
  return y

def base(x,a,b,c):
  return (a*x**2)+(b*x)+c

res, cov = curve_fit(base, x, y)  #Para la funcion cuadratica:
res, sol1

(array([3.04171866, 5.04229335, 3.91439272]),
 array([3.04171871, 5.04229284, 3.91439388]))

In [ ]:
#Los resultados son muy cercanos teniendo una precision de 10^6, por lo que los minimos cuadrados para la cuadratica
#son una muy buena aproximacion, si consideramos el curve fit como exacto

In [131]:
file = '/content/drive/MyDrive/Colab Notebooks/Datos/MinimosLineal.txt'
file

'/content/drive/MyDrive/Colab Notebooks/Datos/MinimosLineal.txt'

In [132]:
data = pd.read_csv(file,sep=' ')
data.columns = ['x','y']

In [133]:
x = np.array(data['x'])
y = np.array(data['y'])

In [134]:
def base2(x,a,b):
  return (a*x)+b

sol2=GetFit(x,y,1)
sol2=np.flip(sol2)

res, cov = curve_fit(base2, x, y)  #Para la funcion lineal:
res, sol2

(array([ 2.13074682, -5.20732248]), array([ 2.13074682, -5.20732249]))

In [ ]:
#Los resultados son muy cercanos teniendo una precision de 10^7, por lo que los minimos cuadrados para la lineal
# son una aproximacion aun mejor que la cuadratica teniendo mayor presicion en los valores de a y b, si consideramos el curve fit como exacto